spring:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
